# Variables
@baseUrl = http://localhost:3333

### Health check
# @name healthCheck
GET {{baseUrl}}/health

###

# Get Rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
    "name": "Sala de teste",
    "description": "Essa é uma sala de teste"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###

# Get room questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# Create question
# @name createQuestion
POST {{baseUrl}}/rooms/45bb4c23-8ebd-43ef-0bba-bb4fff12e3af/questions
Content-Type: application/json

{
    "question": "O que é Vue.js e a sua diferença em relação ao Angular?"
}
###